### ISSUE TITLE
Unable to start the server.

### ISSUE THREAD

**Issue by N07070** [dhoelzgen/snake#1]
Hello,

When I try to run the server; I get this error 

```
(node) sys is deprecated. Use util instead.
17 Dec 18:38:36 - socket.io ready - accepting connections
(node) util.puts is deprecated. Use console.log instead.
Server running on port 5000
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:843
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1225:19)
    at listen (net.js:1274:10)
    at Server.listen (net.js:1370:5)
    at Function.Flashsocket.init (snake/node_modules/socket.io/lib/socket.io/transports/flashsocket.js:44:17)
    at snake/node_modules/socket.io/lib/socket.io/listener.js:49:54
    at Array.forEach (native)
    at new module.exports (snake/node_modules/socket.io/lib/socket.io/listener.js:46:27)
    at Object.exports.listen (snake/node_modules/socket.io/lib/socket.io/index.js:11:10)
```

**Comment by ghost** [comment]
I've updated this project. Find it here: https://github.com/mhsjlw/JavaScript-Snake
